### PR TITLE
Get rid of old ant tests

### PR DESCRIPTION
**Pull request by davigonz**
The tests removed in this PR are not used anymore since building via ant is old-style and not supported by Travis.

It would be great to use library tests with more modern technologies in a short, medium term.

Needed to merge #198 

Needs https://github.com/owncloud/android/pull/2343

### CODE REVIEW

**Comment by davigonz** [comment]
@DeepDiver1975 we do not longer need `test_client` submodule, can you delete it from security/snyk?

**Comment by jesmrec** [comment]
App works in a stable way after removing this stuff.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 we do not longer need `test_client` submodule, can you delete it from security/snyk?

Looking into this .... I can merge this PR for you right away with my admin rights .... let me know ...

**Comment by davigonz** [comment]
> Looking into this .... I can merge this PR for you right away with my admin rights .... let me know ...

Yes, but if you merge this PR for me and `security/snyk` is still expecting `test_client` module in the coming PRs, I will have to ping you to merge every PR from now on 😄

**Comment by DeepDiver1975** [comment]
> Yes, but if you merge this PR for me and `security/snyk` is still expecting `test_client` module in the coming PRs, I will have to ping you to merge every PR from now on smile

should no long pop up in future prs - let's merge and we will see ...

**Comment by davigonz** [comment]
> should no long pop up in future prs - let's merge and we will see ...

@DeepDiver1975 there was a [MR pending](https://github.com/owncloud/android-library/pull/212) before this :grimacing:, would it be possible to revert this without having new commits? The point is that we have to merge master into stable and the last commit should be f3e8374429349903eeb85e47a52718433cc7ff9c

**Comment by DeepDiver1975** [comment]
> would it be possible to revert this without having new commits?

no

**Comment by DeepDiver1975** [comment]
sorry for this

**Pull request merged**
