### PR TITLE
Support to access display name of stored accounts

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
Solved, from my POV. Supporting owncloud/android#1709.

Please, @owncloud/android-developers , review.

**Comment by AndyScherzinger** [comment]
Looks good, does the code change imply that username gets replaces by real name? I guess even though I don't know any use case atm there might still be a change for situations for both.

**Comment by davivel** [comment]
Not exactly, the operation was always reading more information than the user name. Moreover, the field we were reading to get the user name was the display name, but for the server environments where was needed, they were always the same.

I will rename the operation, it's misleading.

**Comment by davivel** [comment]
@AndyScherzinger , let me know if it's better now.

**Comment by AndyScherzinger** [comment]
:smiley: :+1:

**Pull request merged**
