### PR TITLE
Fix non alphanumeric chars in password

### PR DESCRIPTION
**Pull request by malkomich**
Replication of PR #114 of @LukeOwncloud in official repo in order to have the right travis config to assure tests are passed.

### CODE REVIEW

**Comment by davivel** [comment]
:+1:

**Comment by malkomich** [comment]
Hi @jesmrec, you can test it ;)

**Comment by AndyScherzinger** [comment]
:+1: 
...one thing though, shouldn't "UTF-8" be converted into a constant, living in OwnCloudCredentials ? :smiley:

**Comment by davivel** [comment]
>  shouldn't "UTF-8" be converted into a constant, living in OwnCloudCredentials

@AndyScherzinger , could you commit yourself? 

Thanks

**Comment by AndyScherzinger** [comment]
@davivel DONE :) I wasn't sure if i can "just commit" changes to this PR or any other PR by the core team but I am happy to do so :+1:

**Comment by davivel** [comment]
Tiny things are fine to add, specially since we all know each other in this PR. I would have committed myself, but was a busy day... Thanks!

Tons of :+1:s here, time for QA, @jesmrec

**Comment by davivel** [comment]
This was now also approved by QA. Going in.

**Pull request merged**
