### PR TITLE
Updated README.md with new policy: PRs should go to master, no more t…

### PR DESCRIPTION
**Pull request by davivel**
…o develop

### CODE REVIEW

**Comment by davivel** [comment]
Calling @masensio , @rperezb , @purigarcia

**Comment by davivel** [comment]
@AndyScherzinger , we know, but we are dropping that naming scheme to embrace the same as in the core repository, that's what most of the ownCloud contributors expect.

**Comment by masensio** [comment]
:+1:

**Comment by rperezb** [comment]
+1

**Pull request merged**
