### PR TITLE
Show logcat live

### PR DESCRIPTION
**Pull request by hannesa2**
It updates logcat content during observation

### QA

- [x] (1) Clear does not work for Logcat https://github.com/owncloud/android-library/pull/361#issuecomment-746211469 [FIXED]

### CODE REVIEW

**Review by abelgardep — APPROVED** [review]
Thanks for updating it 👍

**Comment by jesmrec** [comment]
### (1)

After updating to 2.2.1, the `Clear log` option stop working within the `Logcat` tab. `Logfile` works fine:

Dec-16-2020 13-23-29

@hannesa2 could you take a look?

**Comment by hannesa2** [comment]
> After updating to 2.2.1, the `Clear log` option stop working within the `Logcat` tab. `Logfile` works fine:

The system writes permanent into logcat, and when you clear what do you expect ?
In my point of view a clear log with logcat makes no sense any more. What do you think ?

**Comment by jesmrec** [comment]
I expected same behaviour as `master`:

Dec-16-2020 13-38-56

About stop writing in LogCat, would we lose information about crashes or system regards in problems?  CC @abelgardep

**Comment by hannesa2** [comment]
Thank you for the catch, I fixed it

**Comment by jesmrec** [comment]
Problem fixed. Now, logcat logs are updated "on the fly"

Approved.

Thanks fort he contribution @hannesa2 !!

**Comment by jesmrec** [comment]
After checking again the feature i've realised that after cleaning the Logcat, it stops updating the logs "on live". Is there something wrong @hannesa2 ?

Dec-17-2020 12-35-32

**Comment by hannesa2** [comment]
If there is no new output,  it can't show nothing new.

Do you expect something. In library repo there is s sample app where it logs all the time.
If it works there, it logs on your side as well

**Comment by hannesa2** [comment]
The sample works like this, and yes, it has some permanent background logging

logloop

**Comment by jesmrec** [comment]
ok, what is strange for me is that before cleaning, logs are refreshed every second/two seconds. Then, no log is refreshed as you can see in the GIF. I will take another look, just in case.

**Comment by jesmrec** [comment]
Let's move this forward. Thanks again @hannesa2 !

**Pull request merged**
