### PR TITLE
Bring back storagePath argument in startLogging

### PR DESCRIPTION
**Pull request by przybylski**
This is a part of  https://github.com/owncloud/android/issues/10 which i'm currently working on

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@przybylski Welcome back! :wink: Can I ask you to fix the breaking unit test? THX

**Comment by jancborchardt** [comment]
Yeeeha! :D @davivel @masensio @tobiasKaminsky @AndyScherzinger check it out – @przybylski is back, the person who wrote the original ownCloud Android app. :)

**Comment by przybylski** [comment]
@DeepDiver1975 @jancborchardt Hi! :) Good to be back.

Anyways, I tried to run them on localhost and got server_base_url is null error. Is there some sort of global (resource) which I need to fix in order to get that working ?

BTW the same thing is happening on travis:
Caused by: java.lang.IllegalArgumentException: host parameter is null

**Comment by DeepDiver1975** [comment]
after chatting with @davivel - failing travis is related to the secrets which are used - travis will fail on forks my nature.

@przybylski you still have push access I assume - please open this PR from a non-fork-branch - THX

**Comment by przybylski** [comment]
@DeepDiver1975 I no longer have push access

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I no longer have push access

hmmm ... but you dd sign the contrib agreement back in the old days - right?

**Comment by przybylski** [comment]
AFAIR I did

**Comment by DeepDiver1975** [comment]
@karlitschek can we readd @przybylski ? THX

**Comment by AndyScherzinger** [comment]
Yeah! Welcome back @przybylski ! :)

**Comment by przybylski** [comment]
Any progress on this?

**Comment by tobiasKaminsky** [comment]
@przybylski Also on this PR. It is much easier for all if the PRs are in the repository and writeable by all.
(regarding your question on update: have a look an some other PRs and see how long they are open... They need some time...)

**Comment by jancborchardt** [comment]
@przybylski as with every pull request it’s good to cross-review – everyone should also go through pull requests of other people and review them. :) Then we are much faster.

**Comment by przybylski** [comment]
I know :)
This pull request was closed because i did open new one from repository branch

**Pull request closed without merging**
