### PR TITLE
add missing permission in library

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by hannesa2** [comment]
This `security/snyk` is maximum annoying
image

**Comment by michaelstingl** [comment]
> This `security/snyk` is maximum annoying

@davigonz @DeepDiver1975 is this tool really helpful?

**Comment by hannesa2** [comment]
@davigonz

**Comment by hannesa2** [comment]
@michaelstingl single point of failure ! 
You need at least two of approver, minimum !

**Comment by hannesa2** [comment]
Sorry I don't found the code, where lint shows me the warning (as far as I remember)
I should always past the lint warning. 
Maybe I was wrong, maybe it disappeared ...

Any way I close it, and when I run into again I make a new one

**Comment by hannesa2** [comment]
and I found more, I will add it too
image

**Comment by davigonz** [comment]
> and I found more, I will add it too

I see... but I am wondering why the app is not failing without those permissions

**Comment by hannesa2** [comment]
@davigonz because app delivers it. 

_So it makes sense to have it in lib and not in app for **other** consumer of this lib_

**Comment by hannesa2** [comment]
@davigonz that means after a merge of this, app can remove this permissions

**Comment by davigonz** [comment]
> that means after a merge of this, app can remove this permissions

Are you sure? `AccountManager` and `ConnectivityManager` are being used in the app well.

**Comment by hannesa2** [comment]
In the future library requires it **and** delivers it. The manifest merger in app will get it from lib, so there is no need for specify in app anymore

**Comment by davigonz** [comment]
> The manifest merger in app will get it from lib, so there is no need for specify in app anymore

Then why the manifest merger is not making the library get the permissions from the app, where are already included? I mean, if we do not specify those permissions in the app but in the library, I suspect the code in the app will appear with some kind of error, same as it appeared in the library.

**Comment by hannesa2** [comment]
Again, currently it's in app, but it should be in lib.
With this PR, other consumer of this lib, get everything out of the box just by including the lib. (**and don't have to add it**)
If you have fears, you can check in future app PR if it works.
This PR only fix providing it in lib

**Comment by hannesa2** [comment]
obsolete now https://github.com/owncloud/android-library/pull/180 includes this as well

**Pull request closed without merging**
