### PR TITLE
Use Android separator instead of homemade one

### PR DESCRIPTION
**Pull request by hannesa2**
It's related to https://github.com/owncloud/android/pull/2907

### CODE REVIEW

**Comment by abelgardep** [comment]
Hi  @hannesa2, thanks for this PR. There is still a homemade path separator in [FileUtils](https://github.com/owncloud/android-library/blob/master/owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java) Could you replace it too?

**Comment by hannesa2** [comment]
> Hi @hannesa2, thanks for this PR. There is still a homemade path separator in [FileUtils](https://github.com/owncloud/android-library/blob/master/owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java) Could you replace it too?

@abelgardep It's done

**Comment by abelgardep** [comment]
Bitrise is failing because there are still uses of PATH_SEPARATOR in sample_client, could you check it?

**Comment by hannesa2** [comment]
> Bitrise is failing because there are still uses of PATH_SEPARATOR in sample_client

It's solved now

Btw,  with #304 I would receive an email automatic and there would be no need of an action on your side

**Pull request merged**
