### PR TITLE
remove sample client

### PR DESCRIPTION
**Pull request by theScrabi**
This will remove the sample client from the client library.
Issue: https://github.com/owncloud/android-library/issues/470

### CODE REVIEW

**Comment by hannesa2** [comment]
Does it makes pain ?
I at least like samples which reduces to a minimum

**Comment by theScrabi** [comment]
In some way it does. We don't test the sample client therefore we can not ensure its proper functionality. You could say development on it is already stall for years. However since it is still there we have to fix compile errors on it from time to time in order to get the whole library through CI.
I think we should remove it, or at best move it to a separate repository. @hannesa2 what do you think?

**Comment by hannesa2** [comment]
I at least build `sample_client` on each pull request properly https://github.com/hannesa2/android-library/runs/5395585442?check_suite_focus=true 

image

For me there is no pain

**Comment by jesmrec** [comment]
The point here is not the "no pain it makes". It is whether the sample app is really useful somehow. It was developed many years ago, it's not maintained and we don't know any user/use case in which it is useful. 

At this point, we need a very good reason not to remove it.

**Review by abelgardep — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
Nothing to test from my side here... sample app is out. Just don't forget to update the pointer from the app to the library.

**Pull request merged**
