### PR TITLE
fix empty screen for guest users

### PR DESCRIPTION
**Pull request by theScrabi**
fixes https://github.com/owncloud/android/issues/2167

### CODE REVIEW

**Comment by davigonz** [comment]
@theScrabi have you used a different user to push this PR changes?

screen shot 2018-04-11 at 13 15 41

**Comment by davigonz** [comment]
Code approved, ready to test @jesmrec

**Comment by theScrabi** [comment]
No does it look like it?

**Comment by jesmrec** [comment]
Approved.

**Pull request merged**
