### PR TITLE
Copy operation

### PR DESCRIPTION
**Pull request by Stoyicker**
Adds copy operation support.

### CODE REVIEW

**Comment by davivel** [comment]
We'd like to push this into higher priority. @Stoyicker , could you merge develop in, please?

For the next time, could you disable automatic formatting? It makes reviews harder. We only try to keep two rules in formatting: use TAB for indentations (not SPACEs), and line length lesser or equal than 120 characrters.

The fail in Travis seems to be due to the private test credentials, we'll relaunch it when needed.

Thanks!

**Comment by davivel** [comment]
Apart from the merge, seems OK to validate.

**Comment by Stoyicker** [comment]
I am really busy these days so I probably will not be able to work on merging this until the weekend of next week or so. But will do.

**Comment by masensio** [comment]
The same as https://github.com/owncloud/android/pull/777#issuecomment-128286846

This PR has a lot of conflicts because the branch is outdated. It should be necessary to updated with the last version of the develop branch.
@Stoyicker, no worries I've created the branch copy_operation_pr_777_with_develop for testing the copy feature.
@purigarcia the branch copy_operation_pr_777_with_develop is ready to be test. :)

**Comment by davivel** [comment]
Closed in favor of #82 , after rebasing and minor fixes. 

Thanks, @Stoyicker

**Pull request closed without merging**
