### PR TITLE
Updated graddle wrapper and plugin versions from security recommendation

### PR DESCRIPTION
**Pull request by davivel**
Details in https://docs.gradle.org/2.14/release-notes#local-privilege-escalation-when-using-the-daemon

### CODE REVIEW

**Comment by davivel** [comment]
cc @owncloud/android-developers 

No functional change, @jesmrec .

**Comment by AndyScherzinger** [comment]
you need to move from mavenCentral() to jcenter() in the build.gradle files, since maven central doesn't have the latest plugin version (yet) and is afaik the new default for Android development.

**Comment by davivel** [comment]
All-in!

**Comment by jesmrec** [comment]
@davivel only internal version changes and the inclusion of jcenter as default repo for gradle. Don't wait if you can merge!! :)

**Comment by davivel** [comment]
🍿

**Comment by davivel** [comment]
Let's go.

**Pull request merged**
