### PR TITLE
Finish remove Android 4.4 support

### PR DESCRIPTION
**Pull request by hannesa2**
Your Bitrise is a black box and I don't know what you test. 
But I know, you don't run
` ./gradlew clean build`

otherwise you will see

image

Needed for: https://github.com/owncloud/android/pull/2768

### CODE REVIEW

**Comment by michaelstingl** [comment]
> Your Bitrise is a black box and I don't know what you test.

Seems there is a way to have the Bitrise project public. I opened a new issue: https://github.com/owncloud/android/issues/2767

**Comment by abelgardep** [comment]
You are right @hannesa2, i forgot to update sample client gradle. Thanks.

**Comment by davigonz** [comment]
@abelgardep I guess we need a PR in the app repo as well

**Comment by davigonz** [comment]
Merged, thanks for the contribution @hannesa2

**Comment by hannesa2** [comment]
Thank you, now it build properly for my account 👍 
image

**Pull request merged**
