### PR TITLE
Allow asynchronous execution without handler

### PR DESCRIPTION
**Pull request by mendhak**
Currently `RemoteOperation.execute` requires a `Handler` so that it can post about an operation being finished - this almost always requires it being invoked from an activity or service. 

When invoking this from an isolated background thread, there is no `Handler` available.  This `execute` overload removes the `Handler` argument so that it can be called from such background threads. 

Reference: Issue #64

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@davivel this change is green on https://github.com/owncloud/android-library/pull/95 

- [ ] need more :question: 
- [ ] ready to test :question: 

THX

**Comment by mendhak** [comment]
@DeepDiver1975 - how did you get the builds green, I keep getting [timeouts](https://travis-ci.org/mendhak/owncloud-android-library/builds/105852339#L1117)

I've updated the code so that the original `execute` is more relaxed as asked in #95

**Comment by davivel** [comment]
@mendhak , happy to read you again :)

Don't worry about the fail of Travis, I think it's an expected problem for PRs coming from external repositories. There are a couple of secure variables in the Travis setup that can't be decrypted from the other repositories and make the automated tests fail there. I'll test by myself and override the result if correct.

If I recall correctly, you already signed the contributor agreement in the past, right? Would you mind to sign it again in the link https://cla-assistant.io/owncloud/android-library?pullRequest=77 ? I think it's the same agreement, but integrated with the Github workflow.

Could you also rebase on master?

**Comment by davivel** [comment]
Yes, I can confirm, tests pass correctly.

**Comment by mendhak** [comment]
Hi thanks for looking, I lazily clicked the 'update branch', thought it would rebase.  Sorry :disappointed: 

CLA signed though.

**Comment by davivel** [comment]
No problem, @mendhak , will do it.

I'll update the introductory docs to join easily to our git workflow.

**Comment by davivel** [comment]
In. Thank you very much, @mendhak :)

**Pull request merged**
