### PR TITLE
Update logcat

### PR DESCRIPTION
**Pull request by hannesa2**
I spitted the lib in two libraries. You don't need the Crashlytic part.
Additional some minor improvements are included

Needed for https://github.com/owncloud/android/pull/2933

### CODE REVIEW

**Comment by abelgardep** [comment]
Hi @hannesa2, is there any relevant change we should be aware of?

**Comment by hannesa2** [comment]
In my point of view not. 
As I already wrote, I splited the lib. Now yuo have not Crashlytics stuff included

**Comment by jesmrec** [comment]
With this PR, log filtering is not working as expected. Check the following animation:

ezgif com-optimize (6)

every log level shows traces about the levels above, that should be hidden by filtering.

**Comment by hannesa2** [comment]
When you scroll to the right, I expect a `w:` `e:` or similar in the text. Am I right ?

**Comment by jesmrec** [comment]
> When you scroll to the right, I expect a w: e: or similar in the text. Am I right ?

i do not get what you mean. What i expect is

- If i filter by `Info`, i will see `Info`, `Warning` and `Error` traces. No `Debug` traces
- If i filter by `Warning`, i will see `Warning` and `Error` traces. No `Debug` and `Info` traces
etc...

this is not happening. i see traces from all levels, whatever the filter i set.

**Comment by jesmrec** [comment]
OTOH, why are you adding all these tags to the official repo? https://github.com/owncloud/android/tags

**Comment by hannesa2** [comment]
> OTOH, why are you adding all these tags to the official repo? https://github.com/owncloud/android/tags

Sorry, this was my mistake, now they are gone.
I did a `git push --tags` but they where pushed to `upstream` not to my `origin`. I try to avoid this in the future

Btw, I deleted them, but when one of you have this in his local repo and will do a `git push --tags` they will appear again  😞

**Comment by hannesa2** [comment]
> OTOH, why are you adding all these tags to the official repo? https://github.com/owncloud/android/tags

Or because `git push --tags` is always pushed to `origin` I've an other possible explanation:

Someone has my fork as an additional remote in his repo, and did a `git push --tags` on his repo and pushed it to this origin.
Then my tags are pushed to this repo. And of course it looks like it was me. (the commit yes, the push not)

**Comment by jesmrec** [comment]
thanks for the explanation, it makes sense.

**Comment by jesmrec** [comment]
About this one: https://github.com/owncloud/android-library/pull/330#issuecomment-651725527

any way to fix it?

**Comment by hannesa2** [comment]
I found the reason. With this commit https://github.com/AppDevNext/Logcat/pull/51/commits/07ce64b61ffd1d00aacec828176ba3e9cc625d57 (case insensitive search) even lowercase are included

image

**Comment by hannesa2** [comment]
This is the fix https://github.com/AppDevNext/Logcat/pull/60

**Comment by hannesa2** [comment]
@jesmrec 
With `2.0.3`it should work now

**Comment by hannesa2** [comment]
I guess you know what's my opinion about bitrise.

image

My fork with Github actions has no issue and it's public/transparent and faster
https://github.com/hannesa2/android-library/pull/1/checks?check_run_id=835406300

**Comment by jesmrec** [comment]
Ready to go

**Pull request merged**
