### PR TITLE
Setup coverity

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by LukasReschke** [comment]
If somebody wants access just register at https://github.com/owncloud/android-library/commit/5a70062fa8eecd3355eb573acaed39dca6025c65#commitcomment-14307148

**Comment by DeepDiver1975** [comment]
@davivel that bloody merge button on github is :hankey: - we better use rebase local and force push

**Comment by davivel** [comment]
@DeepDiver1975 That I guessed, but it's the first time I noticed it, so I *needed* to touch to know what it did, you know :)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 That I guessed, but it's the first time I noticed it, so I needed to touch to know what it did, you know :)

hehe - sure

**Comment by DeepDiver1975** [comment]
:press_all_the_buttons:

**Comment by davivel** [comment]
Seems really cool!

**Comment by tobiasKaminsky** [comment]
Reminds me of: :-)
"They forgot to ask what the red button is for."
600px-5th_24

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
