### PR TITLE
Bring back logging arguments

### PR DESCRIPTION
**Pull request by przybylski**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Code looks good to me :+1:

**Comment by davivel** [comment]
Seems OK, but I miss a companion PR in the android repo to fix the call to ```startLogging``` in ```MainApp```.

@przybylski , could you rebase this one and update the app?

**Comment by davivel** [comment]
This is rebased now, :+1: from my side.

Requires approval of owncloud/android#1770 by @jesmrec before merging

**Comment by davivel** [comment]
Adaption in app was approved by QA:  owncloud/android#1770

**Pull request merged**
